.class interface abstract Lcom/android/camera/camcorder/CamcorderEncoderProfileFactory;
.super Ljava/lang/Object;
.source "CamcorderEncoderProfileFactory.java"


# virtual methods
.method public abstract createCamcorderAudioProfile$51666RRD5TGMSP3IDTKM8BR3C5MMASJ15THM2RB3DTP68PBI5T1M2RB3DTP68PBI8DGN0T3LE9IL4OBKCKTKOORFDKNMERRFCTM6ABR1DPI74RR9CGNM2S3GECNM6OBDCLP62BRGE9NNGU9FDLIM8QB15T1M2RB3DTP68PBIA1P6UPJ9DHIL0SJFF1SJMAACCDNMQBR1DPI74RR9CGNM6OBDCLP62BR3C5MM6RRICHIN4BQ3C5MM6RRICHIN4GBLCHKMUHBECDNM8PBIA1P6UPJ9DHIJM___$51666RRD5TJMURR7DHIIUOBECHP6UQB45TGN0S3J5THM2RB5E9GIUS3IDTS7IBRDCLI6IO9F8DGMQORFE9I6ASIGE9NMCQBCCL874RROF4TIIJ33DTMIUOBECHP6UQB45THM2RB5E9GIUOR1DLHMUSJ4CLP2UGR1DLHMUSJ4CLP42TB4D5NKARJ3DTI6ASIGE9NMCQBCCKTG____(Lcom/google/android/apps/camera/proxy/media/CamcorderProfileProxy;)Lcom/android/camera/one/v2/cameracapturesession/CameraCaptureSessionModule;
.end method

.method public abstract createCamcorderHfrAudioProfile$51666RRD5TGMSP3IDTKM8BR3C5MMASJ15THM2RB3DTP68PBI5T1M2RB3DTP68PBI8DGN0T3LE9IL4OBKCKTKOORFDKNMERRFCTM6ABR1DPI74RR9CGNM2S3GECNM6OBDCLP62BRGE9NNGU9FDLIM8QB15T1M2RB3DTP68PBIA1P6UPJ9DHIL0SJFF1SJMAACCDNMQBR1DPI74RR9CGNM6OBDCLP62BR3C5MM6RRICHIN4BQ3C5MM6RRICHIN4GBLCHKMUHBECDNM8PBIA1P6UPJ9DHIJM___(Lcom/android/camera/camcorder/CamcorderCaptureRate;Lcom/google/android/apps/camera/proxy/media/CamcorderProfileProxy;)Lcom/android/camera/one/v2/cameracapturesession/CameraCaptureSessionModule;
.end method

.method public abstract createCamcorderHfrVideoProfile(Lcom/google/android/apps/camera/proxy/media/CamcorderProfileProxy;Lcom/android/camera/camcorder/CamcorderCaptureRate;Lcom/google/android/apps/camera/camcorder/CamcorderVideoResolution;)Lcom/android/camera/camcorder/CamcorderVideoEncoderProfile;
.end method

.method public abstract createCamcorderVideoProfile(Lcom/google/android/apps/camera/proxy/media/CamcorderProfileProxy;Lcom/android/camera/camcorder/CamcorderCaptureRate;Lcom/google/android/apps/camera/camcorder/CamcorderVideoResolution;)Lcom/android/camera/camcorder/CamcorderVideoEncoderProfile;
.end method

.method public abstract hasCamcorderHfrVideoProfile(Lcom/google/android/apps/camera/proxy/media/CamcorderProfileProxy;Lcom/android/camera/camcorder/CamcorderCaptureRate;Lcom/google/android/apps/camera/camcorder/CamcorderVideoResolution;)Z
.end method

.method public abstract hasCamcorderVideoProfile(Lcom/google/android/apps/camera/proxy/media/CamcorderProfileProxy;Lcom/android/camera/camcorder/CamcorderCaptureRate;Lcom/google/android/apps/camera/camcorder/CamcorderVideoResolution;)Z
.end method
